
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ダッシュボード - <?=$config->webname?></title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/static/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="/static/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="/static/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html"><?=$config->webname?></a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="/"><i class="fa fa-dashboard fa-fw"></i> ダッシュボード</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">ダッシュボード</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                        ドメインリスト</div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>ドメイン</th>
                                        <th>作成日</th>
                                        <th>更新日</th>
                                        <th>GSLB機能</th>
                                        <th>レコード</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($d_list["domains"] as $val) {?>
                                    <tr>
                                        <td><?=substr($val['name'], 0, -1)?></td>
                                        <td><?=date('Y-m-d h:i:s', strtotime($val['created_at']))?></td>
                                        <td><?=date('Y-m-d h:i:s', strtotime($val['updated_at']))?></td>
                                        <td><?=$val['gslb'] ? '有効' : '無効';?></td>
                                        <td><a href="/index/record/info?id=<?=$val['id']?>&domain=<?=substr($val['name'], 0, -1)?>" class="btn btn-primary btn-sm">レコード設定</a></td>
                                    </tr>
                                <?php }?>
                                </tbody>
                            </table>
                            <!-- /.table-responsive -->
                            <div class="btn btn-default btn-lg btn-block" id="btn-add-domain"  href="">新しいドメインを追加</div>

                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
                <!--添加域名-->
                <!-- Modal -->
                <div class="modal fade" id="domain-add-panel" tabindex="-1" role="dialog" aria-labelledby="domain-add-panel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title" id="domain-edit">新しいドメインを追加</h4>
                            </div>
                            <div class="modal-body">
                                <div class="form-group">
                                    <label>ドメイン</label>
                                    <input id='add-domain' class="form-control" placeholder='conoha.app'>
                                </div>
                                <div class="form-group">
                                    <label>TTL（秒）</label>
                                    <input id='add-ttl' type='number' class="form-control" placeholder='300'>
                                </div>

                                <div class="form-group">
                                    <label>電子メール</label>
                                    <input id='add-email' type="email" class="form-control" placeholder='nico@ni-co.moe'>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">オフ</button>
                                <button type="button" class="btn btn-primary" id='domain-save' data-record-id="">ドメイン追加</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- /.modal -->
                <!--/.添加域名-->

                <!-- 提示框 -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                    <!--提示内容-->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- /.提示框 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="/static/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="/static/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- DataTables JavaScript -->
    <script src="/static/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="/static/vendor/datatables-responsive/dataTables.responsive.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/static/dist/js/sb-admin-2.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    var getAlert = function(status,msg){
        return '<div class="alert alert-'+status+'">'+ msg +'<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button></div>';
    };
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true
        });
        
        $('#btn-add-domain').click(function(){
            $("#domain-add-panel").modal()
        });

        $('#domain-save').click(function(){
            $.ajax({
                url:"/index/index/add",
                async:false,
                method:'post',
                data:{
                    'domain':$('#add-domain').val(),
                    'ttl':$('#add-ttl').val(),
                    'email':$('#add-email').val()
                },
                success:function(data){
                    if(data.status == 1){
                        $("#myModal").modal()
                        $('.modal-dialog').html(getAlert('success',data.msg));
                        setTimeout("window.location.reload();","3000");
                    }
                    if(data.status == 0){
                        alert(data.msg);
                        // $('.modal-dialog').html(getAlert('danger',data.msg));

                    }
                },
                error:function(data){
                    alert('ajax請求エラー');
                }
            });
        });

    });
    </script>

</body>

</html>
